// Generated by CoffeeScript 1.3.1
(function() {
  var lovely_couple_hover_timer, sparkle_animate,
    _this = this;

  lovely_couple_hover_timer = void 0;

  sparkle_animate = function(container) {
    return setInterval(function() {
      return $(container).find('span').each(function(index, element) {
        return $(element).css('color', "rgb(" + (Math.floor(Math.random() * 255)) + "," + (Math.floor(Math.random() * 255)) + "," + (Math.floor(Math.random() * 255)) + ")");
      });
    }, 200);
  };

  $(function() {
    var newtext, text, timer,
      _this = this;
    if ($('.homepage').length > 0) {
      $('.homepage .curtains').delay(1000).fadeOut(4000);
      sparkle_animate($('.the-lovely-couple'));
    }
    if ($('.page').length > 0) {
      $('.page .the-lovely-couple').click(function() {
        return document.location = '/';
      });
      timer = void 0;
      $('.the-lovely-couple').hover(function() {
        return timer = sparkle_animate($('.the-lovely-couple'));
      }, function() {
        var _this = this;
        clearInterval(timer);
        return $('.the-lovely-couple span').each(function(index, element) {
          return $(element).css('color', '');
        });
      });
    }
    if ($('.sparkle').length > 0) {
      text = $('.sparkle').text();
      newtext = '';
      $.each(text.split(''), function(index, character) {
        return newtext = "" + newtext + "<span>" + character + "</span>";
      });
      $('.sparkle').html(newtext);
      return sparkle_animate($('.sparkle'));
    }
  });

}).call(this);
