// Generated by CoffeeScript 1.3.1
(function() {
  var lovely_couple_animate, lovely_couple_hover_timer,
    _this = this;

  lovely_couple_hover_timer = void 0;

  lovely_couple_animate = function() {
    return lovely_couple_hover_timer = setInterval(function() {
      return $('.the-lovely-couple span').each(function(index, element) {
        return $(element).css('color', "rgb(" + (Math.floor(Math.random() * 255)) + "," + (Math.floor(Math.random() * 255)) + "," + (Math.floor(Math.random() * 255)) + ")");
      });
    }, 200);
  };

  $(function() {
    if ($('.homepage').length > 0) {
      $('.homepage .curtains').delay(1000).fadeOut(4000);
      lovely_couple_animate();
    }
    if ($('.page').length > 0) {
      $('.page .the-lovely-couple').click(function() {
        return document.location = '/';
      });
      return $('.the-lovely-couple').hover(function() {
        return lovely_couple_animate();
      }, function() {
        var _this = this;
        clearInterval(lovely_couple_hover_timer);
        return $('.the-lovely-couple span').each(function(index, element) {
          return $(element).css('color', '');
        });
      });
    }
  });

}).call(this);
